name: Release 
on:
  push:
    branches:
      - main
  workflow_dispatch: { }

permissions:
  #TODO something is missing here :)

jobs:
  release-please:
    runs-on: #TODO something is missing here :)
    steps:
      - id: release
        name: Release with release-please
        uses: google-github-actions/release-please-action@v4
        with:
          release-type: simple
      
      #TODO something is missing here :)
     
      - name: Get the latest release tag
        id: latest_release
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/github-script@v7
        with:
          script: |
            const latestRelease = await github.rest.repos.getLatestRelease({
            owner: context.repo.owner,
            repo: context.repo.repo,
            });
            core.setOutput("tag_name", latestRelease.data.tag_name);
     
      - name: Tag major version
        id: update-major-tag
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/publish-action@v0.3.0
        with:
          source-tag: ${{ steps.latest_release.outputs.tag_name }}
